import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect, router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { colors, spacing } from '../../src/constants/theme';
import { SiteHeader } from '../../src/components/SiteHeader';
import { supabase } from '../../src/lib/supabase';

export default function Opportunities() {
  const [items,setItems]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false);
  const load=async(refresh=false)=>{if(refresh)setRefreshing(true);else setLoading(true);if(supabase){const {data}=await supabase.from('opportunities').select('*').order('created_at',{ascending:false}).limit(30);setItems(data||[])}setLoading(false);setRefreshing(false)};
  useFocusEffect(useCallback(()=>{load()},[]));
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>load(true)} tintColor="#fff"/>}>
    <SiteHeader onSearch={()=>router.push('/explore')} />
    <View style={styles.hero}><Text style={styles.kicker}>OPPORTUNITIES</Text><Text style={styles.heading}>Build what comes <Text style={styles.blue}>next.</Text></Text><Text style={styles.sub}>Grants, programs, competitions, events and ways to get involved.</Text></View>
    <View style={styles.ruleRow}><Text style={styles.label}>LATEST</Text><Text style={styles.count}>{items.length ? `${items.length} LISTINGS` : 'OPEN TO ALL'}</Text></View>
    {loading?<ActivityIndicator color="#fff" style={{marginTop:50}}/>:<View>{items.map((item,i)=><Pressable key={item.id||i} onPress={()=>item.url&&router.push(item.url)} style={({pressed})=>[styles.card,pressed&&{opacity:.72}]}><View style={styles.row}><Text style={styles.type}>{item.type||item.category||'OPPORTUNITY'}</Text>{item.deadline&&<Text style={styles.deadline}>{item.deadline}</Text>}</View><Text style={styles.title}>{item.title||item.name}</Text>{(item.description||item.summary)&&<Text style={styles.desc} numberOfLines={3}>{item.description||item.summary}</Text>}<View style={styles.cardFoot}><Text style={styles.more}>VIEW OPPORTUNITY</Text><Ionicons name="arrow-up-right" size={15} color={colors.faint}/></View></Pressable>)}{!items.length&&<View style={styles.empty}><Ionicons name="compass-outline" size={24} color="#fff"/><Text style={styles.emptyTitle}>Nothing new yet.</Text><Text style={styles.desc}>New opportunities will appear here from the BitBuzz newsroom.</Text></View>}</View>}
    <View style={styles.bottom}><Text style={styles.kicker}>BITBUZZ OPPORTUNITIES</Text><Text style={styles.bottomTitle}>Find something worth building.</Text></View>
  </ScrollView>
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#000'},content:{paddingHorizontal:spacing.page,paddingBottom:60},hero:{paddingTop:44,paddingBottom:30},kicker:{color:colors.accent,fontSize:9,fontWeight:'800',letterSpacing:2},heading:{color:'#fff',fontSize:40,lineHeight:43,fontWeight:'700',letterSpacing:-1.8,marginTop:10},blue:{color:colors.blue},sub:{color:colors.muted,fontSize:14,lineHeight:21,marginTop:12,maxWidth:350},ruleRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderTopWidth:1,borderTopColor:colors.line,paddingTop:20,marginBottom:14},label:{color:colors.faint,fontSize:9,fontWeight:'800',letterSpacing:2},count:{color:colors.faint,fontSize:8,fontWeight:'700',letterSpacing:1},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,borderRadius:22,padding:18,marginBottom:12},row:{flexDirection:'row',justifyContent:'space-between',gap:10},type:{color:colors.blue,fontSize:8,fontWeight:'800',letterSpacing:1.4},deadline:{color:colors.faint,fontSize:9},title:{color:'#fff',fontSize:20,lineHeight:24,fontWeight:'700',marginTop:12},desc:{color:colors.muted,fontSize:12,lineHeight:18,marginTop:7},cardFoot:{marginTop:18,paddingTop:13,borderTopWidth:1,borderTopColor:colors.line,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},more:{color:colors.faint,fontSize:8,fontWeight:'800',letterSpacing:1.2},empty:{padding:24,borderRadius:22,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line},emptyTitle:{color:'#fff',fontSize:20,fontWeight:'700',marginTop:16},bottom:{marginTop:40,paddingTop:32,borderTopWidth:1,borderTopColor:colors.line},bottomTitle:{color:'#fff',fontSize:27,lineHeight:32,fontWeight:'700',letterSpacing:-1,marginTop:9}}
);