import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect, router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { colors, spacing } from '../../src/constants/theme';
import { supabase } from '../../src/lib/supabase';

export default function Opportunities() {
  const [items,setItems]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false);
  const load=async(refresh=false)=>{if(refresh)setRefreshing(true);else setLoading(true);if(supabase){const {data}=await supabase.from('opportunities').select('*').order('created_at',{ascending:false}).limit(30);setItems(data||[])}setLoading(false);setRefreshing(false)};
  useFocusEffect(useCallback(()=>{load()},[]));
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>load(true)} tintColor={colors.accent}/> }>
    <Text style={styles.kicker}>OPPORTUNITIES</Text><Text style={styles.heading}>Build what comes <Text style={styles.accent}>next.</Text></Text><Text style={styles.sub}>Grants, programmes, competitions and ways to get involved — with deadlines that don't get buried.</Text>
    <View style={styles.rule}><Text style={styles.label}>OPEN NOW</Text><Text style={styles.count}>{items.length ? `${items.length} LISTINGS` : 'LIVE FEED'}</Text></View>
    {loading?<ActivityIndicator color={colors.accent} style={{marginTop:50}}/>:<>{items.map((item,i)=><Pressable key={item.id||i} onPress={()=>item.url&&router.push(item.url)} style={({pressed})=>[styles.card,pressed&&{opacity:.68}]}><View style={styles.row}><Text style={styles.type}>{item.type||item.category||'OPPORTUNITY'}</Text>{item.deadline&&<Text style={styles.deadline}>{item.deadline}</Text>}</View><Text style={styles.title}>{item.title||item.name}</Text>{(item.description||item.summary)&&<Text style={styles.desc} numberOfLines={3}>{item.description||item.summary}</Text>}<View style={styles.cardFoot}><Text style={styles.more}>VIEW OPPORTUNITY</Text><Ionicons name="arrow-up-right" size={16} color={colors.accent}/></View></Pressable>)}{!items.length&&<View style={styles.empty}><Ionicons name="compass-outline" size={25} color={colors.accent}/><Text style={styles.emptyTitle}>Nothing new yet.</Text><Text style={styles.desc}>New opportunities will appear here from the BitBuzz newsroom.</Text></View>}</>}
    <View style={styles.footer}><Text style={styles.kicker}>BITBUZZ OPPORTUNITIES</Text><Text style={styles.footerTitle}>Find something worth building.</Text></View>
  </ScrollView>
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.bg},content:{paddingTop:112,paddingHorizontal:spacing.page,paddingBottom:128},kicker:{color:colors.accent,fontSize:11.5,fontWeight:'700',letterSpacing:.9},heading:{color:colors.text,fontSize:36,lineHeight:37,fontWeight:'800',letterSpacing:-1.7,marginTop:6},accent:{color:colors.accent},sub:{color:colors.muted,fontSize:17,lineHeight:26,marginTop:12},rule:{marginTop:34,paddingTop:16,borderTopWidth:1,borderTopColor:colors.line,flexDirection:'row',justifyContent:'space-between'},label:{color:colors.faint,fontSize:11.5,fontWeight:'700',letterSpacing:.9},count:{color:colors.faint,fontSize:11,fontWeight:'700',letterSpacing:.7},card:{backgroundColor:colors.surface,borderRadius:24,padding:22,marginTop:12},row:{flexDirection:'row',justifyContent:'space-between',gap:10},type:{color:colors.blue,fontSize:11.5,fontWeight:'700',letterSpacing:.9},deadline:{color:colors.faint,fontSize:12},title:{color:colors.text,fontSize:21,lineHeight:25,fontWeight:'700',letterSpacing:-.8,marginTop:12},desc:{color:colors.muted,fontSize:15.5,lineHeight:23,marginTop:9},cardFoot:{marginTop:18,paddingTop:15,borderTopWidth:1,borderTopColor:colors.line,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},more:{color:colors.faint,fontSize:11,fontWeight:'700',letterSpacing:.8},empty:{marginTop:12,padding:28,borderRadius:22,backgroundColor:colors.surface,alignItems:'center'},emptyTitle:{color:colors.text,fontSize:20,fontWeight:'700',marginTop:14},footer:{marginTop:40,paddingTop:30,borderTopWidth:1,borderTopColor:colors.line},footerTitle:{color:colors.text,fontSize:27,lineHeight:32,fontWeight:'700',letterSpacing:-1,marginTop:10}}
);