import { useCallback, useState } from 'react';
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, router } from 'expo-router';
import { colors, media, spacing } from '../../src/constants/theme';
import { getSavedArticles } from '../../src/lib/bookmarks';
import { supabase } from '../../src/lib/supabase';

export default function Profile() {
  const [savedCount,setSavedCount]=useState(0); const [email,setEmail]=useState<string|null>(null); const [loading,setLoading]=useState(true);
  useFocusEffect(useCallback(()=>{let active=true;(async()=>{const [saved,session]=await Promise.all([getSavedArticles(),supabase?.auth.getSession()]);if(!active)return;setSavedCount(saved.length);setEmail(session?.data.session?.user.email??null);setLoading(false)})();return()=>{active=false}},[]));
  const signOut=async()=>{await supabase?.auth.signOut();setEmail(null)};
  const initials=email?email.slice(0,2).toUpperCase():'BB';
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <Text style={styles.kicker}>YOUR BITBUZZ</Text><View style={styles.identity}><Image source={{uri:media.logo}} style={styles.avatar}/><View style={styles.identityCopy}><Text style={styles.name}>{email||'BitBuzz Reader'}</Text><Text style={styles.role}>{email?'Signed in · reader account':'Reading as a guest'}</Text></View><Pressable onPress={()=>router.push('/settings')} style={styles.settings}><Ionicons name="settings-outline" size={19} color={colors.text}/></Pressable></View>
    {!email?<View style={styles.account}><Text style={styles.accountKicker}>KEEP WHAT YOU READ</Text><Text style={styles.accountTitle}>Save stories. Follow desks. Build a streak.</Text><Text style={styles.accountText}>Reading works without an account. Sign in when you want the features that follow you around.</Text><Pressable onPress={()=>router.push('/auth')} style={styles.cta}><Text style={styles.ctaText}>CREATE A FREE ACCOUNT</Text><Ionicons name="arrow-forward" size={15} color={colors.onAccent}/></Pressable></View>:<View style={styles.account}><Text style={styles.accountKicker}>CURRENT RUN</Text><View style={styles.streakRow}><Text style={styles.streak}>7</Text><Text style={styles.streakLabel}>days unbroken</Text></View><View style={styles.week}>{['M','T','W','T','F','S','S'].map((d,i)=><View key={`${d}${i}`} style={styles.day}><View style={[styles.dayFill,i===6&&styles.dayOff]}/><Text style={styles.dayLabel}>{d}</Text></View>)}</View></View>}
    <View style={styles.stats}><Stat value={loading?'—':String(savedCount)} label="Saved"/><Stat value="—" label="Stories read"/><Stat value="—" label="Hours"/></View>
    <View style={styles.menu}><Menu icon="bookmark-outline" label="Saved stories" value={String(savedCount)} onPress={()=>router.push('/saved')}/><Menu icon="notifications-outline" label="Alerts" value="2" onPress={()=>router.push('/notifications')}/><Menu icon="settings-outline" label="Settings" onPress={()=>router.push('/settings')}/></View>
    {email&&<Pressable onPress={signOut} style={styles.signOut}><Text style={styles.signOutText}>SIGN OUT</Text></Pressable>}
    <View style={styles.about}><Text style={styles.kicker}>ABOUT BITBUZZ</Text><Text style={styles.aboutTitle}>Science. Technology. Space. Innovation.</Text><Text style={styles.aboutText}>A student-run newsroom built for people who are curious about what comes next.</Text></View>
  </ScrollView>;
}
function Stat({value,label}:{value:string;label:string}){return <View style={styles.stat}><Text style={styles.value}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>}
function Menu({icon,label,value,onPress}:{icon:any;label:string;value?:string;onPress?:()=>void}){return <Pressable onPress={onPress} style={({pressed})=>[styles.menuRow,pressed&&{opacity:.65}]}><Ionicons name={icon} size={19} color={colors.text}/><Text style={styles.menuText}>{label}</Text>{value&&<Text style={styles.valueSmall}>{value}</Text>}<Ionicons name="chevron-forward" size={16} color={colors.faint}/></Pressable>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.bg},content:{paddingTop:112,paddingHorizontal:spacing.page,paddingBottom:128},kicker:{color:colors.blue,fontSize:11.5,fontWeight:'700',letterSpacing:.9},identity:{marginTop:18,flexDirection:'row',alignItems:'center',gap:14},avatar:{width:64,height:64,borderRadius:32},identityCopy:{flex:1},name:{color:colors.text,fontSize:25,fontWeight:'800',letterSpacing:-1.2},role:{color:colors.muted,fontSize:14,marginTop:4},settings:{width:42,height:42,borderRadius:21,backgroundColor:colors.surface2,alignItems:'center',justifyContent:'center'},account:{marginTop:24,padding:24,borderRadius:26,backgroundColor:colors.accentSurface},accountKicker:{color:colors.accent,fontSize:11.5,fontWeight:'700',letterSpacing:.9},accountTitle:{color:colors.text,fontSize:22,lineHeight:26,fontWeight:'700',letterSpacing:-.9,marginTop:11},accountText:{color:colors.muted,fontSize:15.5,lineHeight:23,marginTop:9},cta:{height:50,marginTop:18,borderRadius:15,backgroundColor:colors.accent,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},ctaText:{color:colors.onAccent,fontSize:11.5,fontWeight:'800',letterSpacing:.6},streakRow:{flexDirection:'row',alignItems:'baseline',gap:10,marginTop:12},streak:{color:colors.text,fontSize:52,fontWeight:'700',letterSpacing:-3},streakLabel:{color:colors.muted,fontSize:17,fontWeight:'600'},week:{flexDirection:'row',gap:6,marginTop:20},day:{flex:1,alignItems:'center',gap:7},dayFill:{width:'100%',height:30,borderRadius:9,backgroundColor:colors.accent},dayOff:{backgroundColor:'rgba(255,255,255,.09)'},dayLabel:{color:colors.faint,fontSize:11.5,fontWeight:'600'},stats:{flexDirection:'row',gap:10,marginTop:12},stat:{flex:1,padding:18,backgroundColor:colors.surface,borderRadius:20},value:{color:colors.text,fontSize:23,fontWeight:'700'},statLabel:{color:colors.faint,fontSize:12.5,marginTop:7},menu:{marginTop:14,borderRadius:18,backgroundColor:colors.surface,overflow:'hidden'},menuRow:{minHeight:56,paddingHorizontal:17,flexDirection:'row',alignItems:'center',gap:14,borderBottomWidth:1,borderBottomColor:colors.line},menuText:{color:colors.text,fontSize:16.5,fontWeight:'500',flex:1},valueSmall:{color:colors.faint,fontSize:13},signOut:{height:50,marginTop:14,borderRadius:15,backgroundColor:colors.surface2,alignItems:'center',justifyContent:'center'},signOutText:{color:colors.alert,fontSize:12,fontWeight:'700',letterSpacing:.7},about:{marginTop:40,paddingTop:30,borderTopWidth:1,borderTopColor:colors.line},aboutTitle:{color:colors.text,fontSize:24,lineHeight:29,fontWeight:'700',letterSpacing:-.8,marginTop:9},aboutText:{color:colors.muted,fontSize:15.5,lineHeight:23,marginTop:9}}
);