import { useCallback, useState } from 'react';
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { colors, spacing } from '../../src/constants/theme';
import { getSavedArticles, SavedArticle } from '../../src/lib/bookmarks';

export default function Saved() {
  const [saved, setSaved] = useState<SavedArticle[]>([]);
  const [loading, setLoading] = useState(true);
  useFocusEffect(useCallback(() => { let active = true; setLoading(true); getSavedArticles().then(items => { if (active) { setSaved(items); setLoading(false); } }); return () => { active = false; }; }, []));
  const minutes = saved.length * 5;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <Text style={styles.kicker}>YOUR LIBRARY</Text><Text style={styles.heading}>Saved</Text>
    <View style={styles.queue}><Text style={styles.queueKicker}>READ-LATER QUEUE</Text><Text style={styles.queueTitle}>{saved.length} {saved.length === 1 ? 'story' : 'stories'}, {minutes} minutes</Text><Text style={styles.queueSub}>Keep the good stuff for the bus, the metro, or offline.</Text></View>
    {loading ? <ActivityIndicator color={colors.accent} style={{marginTop:60}}/> : saved.length === 0 ? <View style={styles.empty}><View style={styles.icon}><Ionicons name="bookmark-outline" size={24} color={colors.accent}/></View><Text style={styles.emptyTitle}>Nothing saved yet.</Text><Text style={styles.emptyText}>Tap the bookmark on any BitBuzz story and it lands here.</Text><Pressable onPress={()=>router.push('/')} style={styles.cta}><Text style={styles.ctaText}>BROWSE STORIES</Text><Ionicons name="arrow-forward" size={15} color={colors.onAccent}/></Pressable></View> : saved.map(item => <Pressable key={item.id} onPress={()=>router.push(`/article/${item.slug}`)} style={({pressed})=>[styles.row,pressed&&{opacity:.65}]}><View style={styles.copy}><Text style={styles.category}>{item.categories?.name || 'BITBUZZ'}</Text><Text style={styles.title}>{item.title}</Text><Text style={styles.meta}>Saved · cached for later</Text></View>{item.cover_image_url ? <Image source={{uri:item.cover_image_url}} style={styles.image}/> : <View style={[styles.image,styles.fallback]}><Ionicons name="newspaper-outline" size={20} color={colors.faint}/></View>}<Ionicons name="chevron-forward" size={16} color={colors.faint}/></Pressable>)}
    <View style={styles.footer}><Text style={styles.footerTitle}>Curiosity today.</Text><Text style={styles.footerText}>A better tomorrow.</Text></View>
  </ScrollView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.bg},content:{padding:112,paddingHorizontal:spacing.page,paddingBottom:128},kicker:{color:colors.green,fontSize:11.5,fontWeight:'700',letterSpacing:.9},heading:{color:colors.text,fontSize:36,lineHeight:37,fontWeight:'800',letterSpacing:-1.7,marginTop:5},queue:{marginTop:22,padding:22,borderRadius:24,backgroundColor:colors.greenSurface},queueKicker:{color:colors.green,fontSize:11.5,fontWeight:'700',letterSpacing:.9},queueTitle:{color:colors.text,fontSize:23,fontWeight:'700',letterSpacing:-.9,marginTop:11},queueSub:{color:colors.muted,fontSize:15,lineHeight:23,marginTop:8},empty:{marginTop:16,padding:28,backgroundColor:colors.surface,borderRadius:22,alignItems:'center'},icon:{width:52,height:52,borderRadius:26,backgroundColor:colors.surface2,alignItems:'center',justifyContent:'center'},emptyTitle:{color:colors.text,fontSize:20,fontWeight:'700',marginTop:16},emptyText:{color:colors.muted,fontSize:15.5,lineHeight:23,textAlign:'center',marginTop:9},cta:{marginTop:18,height:46,paddingHorizontal:20,borderRadius:15,backgroundColor:colors.accent,flexDirection:'row',alignItems:'center',gap:8},ctaText:{color:colors.onAccent,fontSize:12,fontWeight:'800',letterSpacing:.7},row:{minHeight:98,paddingVertical:16,borderBottomWidth:1,borderBottomColor:colors.line,flexDirection:'row',alignItems:'center',gap:12},copy:{flex:1,minWidth:0},category:{color:colors.blue,fontSize:11.5,fontWeight:'700',letterSpacing:.9},title:{color:colors.text,fontSize:16.5,lineHeight:21,fontWeight:'600',letterSpacing:-.4,marginTop:6},meta:{color:colors.faint,fontSize:12,marginTop:7},image:{width:66,height:66,borderRadius:14},fallback:{backgroundColor:colors.surface2,alignItems:'center',justifyContent:'center'},footer:{marginTop:40,padding:26,borderRadius:24,backgroundColor:colors.surface},footerTitle:{color:colors.text,fontSize:22,fontWeight:'700',letterSpacing:-.8},footerText:{color:colors.muted,fontSize:15,marginTop:5}}
);